# Generated by Django 3.0.3 on 2020-06-09 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='manage',
        ),
    ]
