# Generated by Django 3.0.3 on 2020-06-19 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0008_auto_20200619_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='manage',
        ),
    ]
