# Generated by Django 3.0.3 on 2020-06-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dbs',
            field=models.CharField(default='DBS Number', max_length=12, verbose_name='DBS Number'),
        ),
    ]
