# Generated by Django 3.0.3 on 2020-06-08 15:29

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_auto_20200608_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='area',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('AE', 'A&E Nurse'), ('DR', 'Doctor')], default='Blank', max_length=5),
        ),
    ]
